enable-pre-post-scripts: true
nodeOptions: '--experimental-strip-types --disable-warning=ExperimentalWarning'
onlyBuiltDependencies:
  - '@biomejs/biome'
packages:
  - 'config/*'
  - 'examples/*'
  - 'packages/*'
  - '!config/eslint-config'
  - '!config/jest-config'
  - '!config/jest-presets'
  - '!config/lint-staged'
  - '!config/lighthouse-config'
  - '!examples/design-system'
  - '!packages/design-system'
  - '!packages/spotify'
