# name: 'Release'
name: '🏷️  '
description: 'Localized Release'
author: 'JeromeFitz'

inputs:
  GH_TOKEN:
    description: 'Github Token'
    required: true
  NPM_TOKEN:
    description: 'NPM Token'
    required: true
  TURBO_TEAM:
    description: 'ID for Turbo'
    required: true
  TURBO_TOKEN:
    description: 'ID for Turbo'
    required: true

runs:
  using: 'composite'
  steps:
    - name: '🏗️  Build'
      id: release-build
      shell: bash
      env:
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      run: |
        pnpm run build:all \
          --cache-dir=".cache-turbo"
    - name: '🔍 Audit'
      id: audit
      shell: bash
      run: |
        npm audit signatures
    - name: '🏷️  Release'
      id: release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      run: |
        pnpm run semantic-release
