# name: 'Install'
name: '📦️  '
description: 'Localized Install'
author: 'JeromeFitz'

runs:
  using: 'composite'
  steps:
    # - name: '🏪  pnpm store'
    #   id: pnpm-cache
    #   run: |
    #     echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
    # -  name: '🌵  pnpm cahce'
    #    id: pnpm-cache-setup
    #     uses: actions/cache@v3
    #     with:
    #       path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
    #       key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
    #       restore-keys: |
    #         ${{ runner.os }}-pnpm-store-
    - name: '📦️  Dependencies'
      id: dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
