# name: 'Cache'
name: 'ðŸ”ºï¸  '
description: 'Localized Cache (turbo)'
author: 'JeromeFitz'

inputs:
  TURBO_TEAM:
    description: 'ID for Turbo'
    required: true
  TURBO_TOKEN:
    description: 'ID for Turbo'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'ðŸ”ºï¸  Cache (turbo)'
      id: cache-turbo
      uses: actions/cache@v5
      env:
        TURBO_TEAM: ${{ inputs.TURBO_TEAM }}
        TURBO_TOKEN: ${{ inputs.TURBO_TOKEN }}
      with:
        path: .cache-turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        # order of preference => turbo will re-check
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-
          turbo-${{ github.job }}-
          turbo-
