#!/bin/sh
[ -n "$CI" ] && exit 0

FILE_ENV=.env
if [ -f "$FILE_ENV" ]; then
    # shellcheck disable=SC2046
    [ ! -f "$FILE_ENV" ] || export $(grep -v '^#' $FILE_ENV | xargs)
fi

# @todo(husky) In POSIX sh, [[ ]] is undefined.
# shellcheck disable=SC3010
# shellcheck disable=SC2009
if ps -o args= $PPID | grep -E -q ' --no-verify| -n | -n$' ; then
    exit 0
fi

if [ "$HUSKY" = "0" ]; then
    exit 0
fi

if [ ! "$HUSKY__PRE_COMMIT__LINT_STAGED" = "0" ]; then
    pnpm lint-staged
fi
