#!/bin/sh
[ -n "$CI" ] && exit 0

FILE_ENV=.env
if [ -f "$FILE_ENV" ]; then
    # shellcheck disable=SC2046
    [ ! -f "$FILE_ENV" ] || export $(grep -v '^#' $FILE_ENV | xargs)
fi

# @todo(husky) In POSIX sh, [[ ]] is undefined.
# shellcheck disable=SC3010
# shellcheck disable=SC2009
if ps -o args= $PPID | grep -E -q ' --no-verify| -n | -n$' ; then
    exit 0
fi

if [ "$HUSKY" = "0" ]; then
    exit 0
fi

if [ ! "$HUSKY__PRE_COMMIT__LINT_STAGED" = "0" ]; then
    if git status --short | grep --quiet '^MM'; then
        printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
        exit 1;
    fi

    pnpm exec oxfmt --no-error-on-unmatched-pattern

    # safe fixes only: https://oxc.rs/docs/guide/usage/linter/automatic-fixes.html
    NODE_NO_WARNINGS=1 pnpm exec oxlint --fix

    if git diff --name-only --cached | grep package.json --quiet; then
        pnpm syncpack lint
    fi

    git update-index --again
fi
