# name: 'Init'
name: '💽️  '
description: 'Localized Init'
author: 'JeromeFitz'

inputs:
  node-version:
    default: '22'
    description: '🔢  Node version'
    required: true

runs:
  using: 'composite'
  steps:
    - name: '🔧  pnpm: Install'
      id: pnpm-setup
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: '💽️  Node ${{ inputs.node-version }}'
      id: node-setup
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: pnpm-lock.yaml
        cache: 'pnpm'
        node-version: ${{ inputs.node-version }}
