# name: 'Init'
name: '💽️  '
description: 'Localized Init'
author: 'JeromeFitz'

runs:
  using: 'composite'
  steps:
    - name: '🔧  pnpm: Install'
      id: pnpm-setup
      uses: pnpm/action-setup@v5
      with:
        run_install: false

    - name: '💽️  Node ${{ inputs.node-version }}'
      id: node-setup
      uses: actions/setup-node@v6
      with:
        cache-dependency-path: pnpm-lock.yaml
        cache: 'pnpm'
        node-version-file: .nvmrc
