name: '  🌃️  Weekly'
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # ref: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '0 0 * * 1'

env:
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  pull:
    name: '👷️  CI'
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: '🐙️  Checkout'
        id: pull-checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 100

      - name: '💽️  Init'
        id: weekly-init
        uses: JeromeFitz/packages/.github/actions/init@NICE-175

      - name: '📦  Install'
        id: weekly-install
        uses: JeromeFitz/packages/.github/actions/install@NICE-175

      - name: '🔺️  Cache (turbo)'
        id: pull-cache-turbo
        uses: JeromeFitz/packages/.github/actions/cache-turbo@NICE-175
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: '☣️ Biome CI'
        run: pnpm exec biome ci .

      - name: '🚨️  Lint'
        id: weekly-lint
        uses: JeromeFitz/packages/.github/actions/lint@NICE-175
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: '🏗️  Build'
        id: weekly-build
        uses: JeromeFitz/packages/.github/actions/build@NICE-175
        with:
          BUILD_COMMAND: 'build:all'
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: '🏷️  Release'
        id: weekly-release
        uses: JeromeFitz/packages/.github/actions/release@NICE-175
        with:
          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
