name: "  🌃️  Weekly"
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # ref: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: "0 0 * * 1"

env:
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  pull:
    name: "👷️  CI"
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: "🐙️  Checkout"
        id: pull-checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 100
          persist-credentials: false

      - name: "💽️  Init"
        id: weekly-init
        uses: ./.github/actions/init

      - name: "📦  Install"
        id: weekly-install
        uses: ./.github/actions/install

      - name: "🔺️  Cache (turbo)"
        id: pull-cache-turbo
        uses: ./.github/actions/cache-turbo
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: "☣️ Biome CI"
        run: pnpm exec biome ci .

      - name: "🚨️  Lint"
        id: weekly-lint
        uses: ./.github/actions/lint
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: "🧪  Test"
        id: weekly-test
        uses: ./.github/actions/test
        with:
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: "🏷️  Release"
        id: weekly-release
        uses: ./.github/actions/release
        with:
          GH_TOKEN: ${{ env.GH_BOT_TOKEN }}
          NPM_TOKEN: ${{ env.NPM_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
